# eslint configuration
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
    impliedStrict: true
env:
  browser: true
  node: true
  es6: true
  jasmine: true
  jquery: true
plugins:
  - react
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
settins:
  react:
    pragma: h
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  # Preact rules
  react/react-in-jsx-scope: off
  react/no-unknown-property:
    - error
    - ignore:
      - class